# -*- coding: utf-8 -*-
"""
   Description:
        -
        -
"""


class PageCode(object):
    HOME_PAGE = 'HOME_PAGE'
    EXPLORE_LIVE = 'EXPLORE_LIVE'
    EXPLORE_VIDEO = 'EXPLORE_VIDEO'
    EXPLORE_MUSIC = 'EXPLORE_MUSIC'
    EXPLORE_SHORT = 'EXPLORE_SHORT'


class ComponentCode(object):
    VIDEO_BANNER = 'VIDEO_BANNER'
    VIDEO_SLIDER = 'VIDEO_SLIDER'
    VIDEO_SHORT = 'VIDEO_SHORT'
    CHANNELS = 'CHANNELS'
    CHANNELS_WITH_FOLLOW = 'CHANNELS_WITH_FOLLOW'
    SHORT_VERTICAL = 'SHORT_VERTICAL'


class BlockCode(object):
    # Page home
    TOP_NFT = 'BLOCK_TOP_NFT'
    TOP_LIVE = 'BLOCK_TOP_LIVE'
    TOP_MUSIC = 'BLOCK_TOP_MUSIC'
    TOP_VIDEO = 'BLOCK_TOP_VIDEO'
    TOP_SHORT = 'BLOCK_TOP_SHORT'
    POPULAR_CHANNEL = 'POPULAR_CHANNEL'
    # Page explore live
    LIVE_PAGE_BANNER_VIDEOS = 'LIVE_PAGE_BANNER_VIDEOS'
    LIVE_PAGE_SHORT_VIDEOS = 'LIVE_PAGE_SHORT_VIDEOS'
    LIVE_PAGE_SLIDER_VIDEOS = 'LIVE_PAGE_SLIDER_VIDEOS'
    LIVE_PAGE_POPULAR_CHANNELS_WITH_FOLLOW = 'LIVE_PAGE_POPULAR_CHANNELS_WITH_FOLLOW'
    LIVE_PAGE_USER_SHORT_VIDEOS = 'LIVE_PAGE_USER_SHORT_VIDEOS'
    LIVE_PAGE_RECOMMEND_SLIDER_VIDEOS = 'LIVE_PAGE_RECOMMEND_SLIDER_VIDEOS'

    # Page explore shorts
    SHORT_PAGE_ALL = 'SHORT_PAGE_ALL'
